FROM nginx

COPY default.conf /etc/nginx/conf.d/default.conf
COPY upstream.blue /etc/nginx/conf.d/upstream.blue
COPY upstream.green /etc/nginx/conf.d/upstream.green

RUN ln -s /etc/nginx/conf.d/upstream.blue /etc/nginx/conf.d/upstream.conf
