name: Mini Pipeline CD (Docker, self-hosted)

on:
  push:
    branches:
      - test-bluegreen

jobs:
  run-pipeline:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Make scripts executable
        run: |
          chmod +x deploy.sh
          chmod +x health_check.sh
          chmod +x switch.sh

      - name: Show current container
        run: docker ps

      - name: Run blue-green deploy
        run: ./deploy.sh

      - name: Verify service
        run: curl -f -s http://localhost:8080

      - name: Show container after deploy
        run: docker ps
