name: Mini Pipeline CD (Docker, self-hosted)

on:
  push:
    branches: ["main"]

jobs:
  run-pipeline:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Make scripts executable
        run: chmod +x run_all.sh deploy.sh health_check.sh rollback.sh

      - name: Run deploy pipeline
        run: ./run_all.sh
